<?php
function gr_options_general() {

$option = get_option('gr_setup');

?>
<form name="gr_general_options" method="POST" action="">
<?php 
if($_GET['updated'] == '0' && !$option['gr_do_annotation'] ) { 
?><br /><font color="red"><strong>You need to choose the kind of data you want to create!</strong></font><br /><br /><?php
}
if($_GET['tab'] == 'general' ) {
if($_GET['updated'] >= '1') { 
?><br /><font color="red"><strong>Update was successful!</strong></font><br /><br /><?php 
} 
elseif($_GET['updated'] == '0') { 
?><br /><font color="red"><strong>No update was made!</strong></font><br /><br /><?php 
}
}
?>
<br />
<h3>General Options</h3>
<div class="submit">
	&nbsp; &nbsp;<input type="submit" value="<?php echo __('Update &raquo;', 'wpec_goodrelations');?>" name="updategeneral"/>
</div>
<table>
	<tbody>
		<tr>
			<td colspan="2">
				<table style="border: 1px solid darkgray; padding: 5px; padding-bottom: 5px">
					<tbody>
						<tr>
							<td colspan="2">
								<h4>Choose how GoodRelations metadata should be embedded</h4>
							</td>
						</tr>
						<tr>
							<td style="width:425px">
								&nbsp;&nbsp;
								<input type="radio" id="google_checkbox" name="option[gr_do_annotation]" value="automatic" onclick="if(document.getElementById('template_checkbox').checked == 1) {
								document.getElementById('template_field').style.display = '';
								} else {document.getElementById('template_field').style.display = 'none';}"
								<?php if ($option['gr_do_annotation'] == 'automatic') echo "checked"; ?> />
								automatically
							</td>
							<td style="width:600px; height: 20px" rowspan="2">
								<input type="button" id="hook_button" value="Show me hook information" onclick="document.getElementById('hook_information').style.display = ''; this.type = 'hidden';" />
								<div id="hook_information" style="display:none">
									Hooks the annotation of company and store locations to 'get_template_part_loop'
									<br />
									on the first page of the blog and the product data to 'wpsc_product_before_description'
									<br /> in the single product template.
								</div>
								</td>
						</tr>
						<tr>
							<td>
								&nbsp;&nbsp;
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<br/>
								&nbsp;&nbsp;
								<strong>Check this only if you have changed your templates and if you are able to add the GoodRelations specific functions to your own template</strong>
								<br />
								&nbsp;&nbsp;
								<input type="radio" id="template_checkbox" name="option[gr_do_annotation]" value="template" <?php if ($option['gr_do_annotation'] == 'template') echo "checked"; ?> 
								onclick="if(document.getElementById('template_checkbox').checked == 1) {
								document.getElementById('template_field').style.display = '';
								} else {document.getElementById('template_field').style.display = 'none';}"/>
								by adding GoodRelations for WP e-Commerce specific template functions manually
							</td>
						</tr>
						<tr>
							<td colspan="2" id="template_field" style="border: 1px red solid;padding:4px;;<?php if ( $option['gr_do_annotation'] == 'template' ) { echo ""; } else { echo "display:none"; } ?>">
								<br />
								The RDFa Data generated by GoodRelations Plugin for WP E-Commerce will not be shown automatically on product pages and the front page of your WP E-Commerce Shop!
								<br />
								<br />
								You need to add to your product pages and your start page the following functions:
								<br />
								<br />
								<table >
									<thead>
										<tr>
											<td style="width:350px">Name of the function</td>
											<td style="width:320px">Where to put
												<br />
												<br />
											</td>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td style="width:350px">
												<pre>gr_template_company()</pre>
											</td>
											<td style="width:320px">
												To be placed on the frontpage of your blog / WP E-Commerce Store.
												<br />
												Add the function as early as possible in the body-tag of your template!
												<br />
												Take care, that the function is not called more than once!
												<br />
												<br />
											</td>
										</tr>
										<tr>
											<td>
												<pre>gr_template_product(wpsc_the_product_id())</pre>
											</td>
											<td>
												To be placed right after
												<br />
												<pre>&lt;?php while (wpsc_have_products()) :  wpsc_the_product(); ?&gt;</pre>
												within the product loop.
												<br />
												If you have disabled single product pages you need to activate the 
												<br />
												'add metadata on category pages' checkbox and put the function in 
												<br />
												the products_page.php template and single_product.php template, too.
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr height="10px">
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<table width="100%" style="border: 1px solid darkgray; padding: 5px; padding-bottom: 5px">
					<tbody>
						<tr>
							<td colspan="2">
								<h4>Product Fields</h4>
							</td>
						</tr>
						<tr>
							<td>
								&nbsp;&nbsp;
								<input type="checkbox" name="option[gr_field][serialnumber]" value="1" <?php if($option['gr_field']['serialnumber'] == '1') echo "checked"; ?> />
								Show field <a href="http://purl.org/goodrelations/v1#serialNumber" target="_new">serial number</a> while adding/editing products (may be useful if you produce your own products or have serial numbers for your products)
							</td>
							<td>
								&nbsp;
							</td>
						</tr>
						<tr height="10px">
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<table width="100%" style="border: 1px solid darkgray; padding: 5px; padding-bottom: 5px">
					<tbody>
						<tr>
							<td colspan="2">
								<h4>Namespace and Doctype change on page request</h4>
							</td>
						</tr>
						<tr>	
							<td style="width:490px">
								&nbsp;&nbsp;
								<input type="checkbox" id="doctype_checkbox" onclick="if(this.checked == 1) {document.getElementById('doctype_explanation').style.display = 'none'; } else {document.getElementById('doctype_explanation').style.display = ''; }" name="option[do_header][doctype]" value="1" <?php if($option['do_header']['doctype'] == '1') echo "checked"; ?> />
								Change the Doctype of my template with every page request.
								<br />
								<br />
							</td>
							<td id="doctype_explanation" <?php if($option['do_header']['doctype'] == '1') echo 'style="display:none"'; ?>>
								These options make the charset tag xhtml compliant and change the <br />doctype of your template to
								<br />
								<div style="padding:1px; max-width:500px; outline: 1px solid; background-color: white; outline-color: #DFDFDF; outline-bottom-left-radius: 4px 4px; outline-bottom-right-radius: 4px 4px; outline-style: solid; outline-width: 1px; outline-top-left-radius: 4px 4px; outline-top-right-radius: 4px 4px">
									<center><xmp><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN"<?php echo "\n"; ?>"http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd"></xmp></center>
								</div>
							</td>
						</tr>
						<tr>
							<td>
								&nbsp;&nbsp;
								<input type="checkbox" id="checkbox_namespace" onclick="if(this.checked == 1) {document.getElementById('namespace_explanation').style.display = 'none'; } else {document.getElementById('namespace_explanation').style.display = ''; }" name="option[do_header][namespace]" value="1" <?php if($option['do_header']['namespace'] == '1' ) echo "checked"; ?> />
								Change the Namespace of my template with every page request.
								<br />
							</td>
							<td id="namespace_explanation" <?php if($option['do_header']['namespace'] == '1') echo 'style="display:none"'; ?>>
								and add this to the html(xhtml)-tag<br />
								<div style="padding:1px; max-width:500px; outline: 1px solid; background-color: white; outline-color: #DFDFDF; outline-bottom-left-radius: 4px 4px; outline-bottom-right-radius: 4px 4px; outline-style: solid; outline-width: 1px; outline-top-left-radius: 4px 4px; outline-top-right-radius: 4px 4px">
									<center><xmp>xmlns="http://www.w3.org/1999/xhtml" version="XHTML+RDFa 1.0"</xmp></center>
								</div>
							</td>
						</tr>
						<tr>
							<td colspan="2"> 
								<br />
								<i>
									If you are able to change the doctype and the namespace in the template <br />uncheck these two checkboxes and do it! Performance of your page will increase!
								</i>
								<br />
								<br />
							</td>
						</tr>
						<tr height="10px">
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<table width="100%" style="border: 1px solid darkgray; padding: 5px; padding-bottom: 5px">
					<tbody>
						<tr>
							<td colspan="2">
								<h4>Annotation in categories</h4>
							</td>
						</tr>
						<tr>
							<td colspan="2" style="height:50px">
								&nbsp;&nbsp;
								<input type="checkbox" name="option[annotation_in_category]" value="1" <?php if($option['annotation_in_category'] == '1') echo "checked"; ?> />
								add GoodRelations metadata on category pages (e.g. if you have disabled single product pages)
							</td>
						</tr>
						<tr height="10px">
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<table width="100%" style="border: 1px solid darkgray; padding: 5px; padding-bottom: 5px">
					<tbody>
						<tr>
							<td colspan="2">
								<h4>Notify the Web of Linked Data via gr-notify.appspot.com</h4>
							</td>
						</tr>
						<tr>
							<td colspan="2" style="height:50px">
								&nbsp;&nbsp;
								<input type="checkbox" name="option[gr_notify][do]" value="1" onclick="if(this.checked == 1) {document.getElementById('gr_notify').style.display = ''; } else {document.getElementById('gr_notify').style.display = 'none'; }"y <?php if($option['gr_notify']['do'] == '1') echo "checked"; ?> />
								notify the Web of Linked Data
								<div id="gr_notify" style="margin-top: 5px;margin-left: 12px;<?php if($option['gr_notify']['do'] != 1) echo "display:none"; ?>">
									uri of your sitemap.xml &nbsp;&nbsp;
									<input type="text" style="width: 400px" name="option[gr_notify][uri]" value="<?php echo $option['gr_notify']['uri']; ?>" /><br />
									update schedule: &nbsp;&nbsp;
									<select name="option[gr_notify][schedule]" style="width:100px" onchange="document.getElementById('gr_notify_schedule').value=this.options[this.selectedIndex].value; document.getElementById('gr_notify_schedule').disabled=this.selectedIndex!=0">
										<option value="">select ...</option>
										<option value="1">daily</option>
										<option value="7">weekly ( 7 days )</option>
										<option value="30">monthly ( 30 days )</option>
									</select> 
									&nbsp;
									<input style="width:80px" name="option[gr_notify][schedule]" id="gr_notify_schedule" type="text" title="you may enter a schedule in days (min: 1 day)" value="<?php echo $option['gr_notify']['schedule']; ?>" />
									day(s)
									<br />
									contact email (optional): &nbsp;&nbsp;
									<input type="text" name="option[gr_notify][contact]" value="<?php echo $option['gr_notify']['contact']; ?>" />
								</div>
							</td>
						</tr>
						<tr height="10px">
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
<div class="submit">
<input type='hidden' name='gr_admin_action' value='submit_general_options' />
			<?php wp_nonce_field('update-general-options', 'gr-update-general-options'); ?>
&nbsp; &nbsp;<input type="submit" value="<?php echo __('Update &raquo;', 'wpec_goodrelations');?>" name="updategeneral"/>
</div>
<?php

}
?>